Added SUNA data and changed instrument ctd data
voto-ocean-knowledge/deployment-yaml pull request #101
Opened 2022-10-06 13:54 UTC by MOchiara

2022-10-06 13:55 UTC, MOchiara commented
@callumrollo can you help me with this when you have time

2022-10-06 14:23 UTC, callumrollo requested changes

2022-10-06 14:23 UTC, callumrollo commented on mission_yaml/SEA76_M8.yml
> +    units:        %
% is a special character in yml. Enclose it in quotes like "%"

2022-10-07 10:08 UTC, callumrollo approved these changes

2022-10-07 10:09 UTC, merged