Added yaml for SEA44_M72
voto-ocean-knowledge/deployment-yaml pull request #147
Opened 2023-02-06 15:56 UTC by MOchiara

2023-02-06 15:56 UTC, MOchiara commented
@callumrollo Can you check this ?

2023-02-06 16:56 UTC, callumrollo requested changes

2023-02-06 16:56 UTC, callumrollo commented on mission_yaml/SEA44_M72.yml
> +  backscatter:
One small change. I've changed the name of this backscatter variable to `backscatter_scaled` in prep for proper backscatter processing. This block is now:

```
  backscatter_raw:
    source:       FLBBPC_BB_700_COUNT
    long_name:    raw 700 nm wavelength backscatter
    standard_name: raw_700_nm_wavelength_backscatter_in_sea_water
    units:        counts
    coordinates:  time depth latitude longitude
    instrument:    instrument_scatterometer
```

2023-02-07 11:05 UTC, callumrollo approved these changes

2023-02-07 11:05 UTC, merged