all the missing sensors added
voto-ocean-knowledge/deployment-yaml pull request #4
Opened 2021-12-15 09:26 UTC by akmazur

2021-12-15 13:32 UTC, callumrollo commented
Looks great!

2021-12-15 13:32 UTC, callumrollo commented
@Maribaken

2021-12-15 13:36 UTC, callumrollo commented on devices.yaml
> +    long_name: Wetlabs ECO Puck FLNTU
Are you sure this is the right spelling?

2021-12-15 13:37 UTC, callumrollo commented on devices.yaml
> +    long_name: Wetlabs ECO Puck FLNTU
Oh wait, it's fine

2021-12-16 12:26 UTC, callumrollo requested changes
Looks good! Lots of great additions. I've added a few comments for specific lines. Mostly on formatting to make downstream processing easier

2021-12-16 12:26 UTC, callumrollo commented on devices.yaml
> +    calibration_parameters: Chl_DarkCounts = 48 Chl_SF = 0.0121 NTU_DarkCounts = 49 NTU_SF = 0.0060
Let's make these calibration parameters easy to read for downstream users. How about formatting as a dictionary?:

{Chl_DarkCounts : 48,  Chl_SF : 0.0121, NTU_DarkCounts : 49, NTU_SF  0.0060}

2021-12-16 12:26 UTC, callumrollo commented on variables.yaml
> +    precision:     "0.001" #?
Thanks for fixing this! I think I copied it from the GPCTD originally, hence the incorrect values. Can drop the precision field if there's no manufacturer supplied calue for it. These are all "nice to have" extras. The  essentials are:

    source:      
    long_name:    
    standard_name: 
    units:   
    coordinates:  
    
    Which you have

2021-12-16 12:26 UTC, callumrollo commented on variables.yaml
> +    resolution:       "0.001% FS"
What is FS here? Again, feel free drop the precision value if it makes sense for this sensor

2021-12-16 12:26 UTC, callumrollo commented on variables.yaml
> +    precision:     "0.001" #?
If unsure about any value, just leave it out

2021-12-16 12:26 UTC, callumrollo commented on variables.yaml
> -    units:        Celsius
Lets keep this as Celsius, not degree Celsius. Don't wanna risk a mix up with degree (like roll/pitch) later in the processing. It wil get formatted to fancy degree symbol C for plots, fear not!

2021-12-16 12:26 UTC, callumrollo commented on variables.yaml
> +    resolution:      "<1"
Leave out the < sign, just a number is good. Better to have the largest resolution value the manufacturer quotes

2021-12-16 15:13 UTC, Maribaken reviewed
Some comments

2021-12-16 15:24 UTC, callumrollo commented on devices.yaml
>    optics2:
Each deployment will only have one of these blocks for each type, so just calling all of them optics would probably be best. This file will just be a source we copy and paste from, so we don't need every block to have a unique name

2021-12-17 06:17 UTC, akmazur commented on variables.yaml
> +    valid_max:    "42"
I think they updated the datasheet https://rbr-global.com/products/oem/rbrlegato
We should update docs on our server.

2021-12-17 06:26 UTC, akmazur commented on variables.yaml
> +    accuracy:      "0.003" #?
I didn't do any calculations to be honest, that's why I marked it with #? I replaced the accuracy value with 0.02. Cana you double check the resolution we get Marcus?

2021-12-17 12:57 UTC, callumrollo requested changes
Great work! Only things I picked up on are the units in OCR504 and AD2CP blocks to go from m/s to m s-1 etc. After that, I'm happy to see this merged in

2021-12-17 17:17 UTC, Maribaken commented on variables.yaml
> +    valid_max:    "42"
Perfect

2021-12-17 17:31 UTC, Maribaken requested changes
Added comments for units to be changed

2021-12-17 17:31 UTC, Maribaken commented on variables.yaml
> +    units:        W/m^2/nm
W m-2 nm-1

2021-12-17 17:31 UTC, Maribaken commented on variables.yaml
> +    units:        W/m^2/nm
W m-2 nm-1

2021-12-17 17:31 UTC, Maribaken commented on variables.yaml
> +    units:       W/m^2/nm
W m-2 nm-1

2021-12-17 17:31 UTC, Maribaken commented on variables.yaml
> +    units:        μE/m^2/s
μE m-2 s-1

2021-12-17 17:31 UTC, Maribaken commented on variables.yaml
> +    units:        m/s
m s-1

2021-12-17 17:31 UTC, Maribaken commented on variables.yaml
> +    units:        m/s
m s-1

2021-12-17 17:31 UTC, Maribaken commented on variables.yaml
> +    units:        m/s
m s-1

2021-12-17 17:31 UTC, Maribaken commented on variables.yaml
> +    units:        m/s
m s-1

2021-12-17 21:42 UTC, callumrollo approved these changes

2021-12-17 21:45 UTC, merged